"""Perspective-map evaluation of the three-objective integral R2 indicator.

The ideal point is assumed to be translated to the origin, so every
approximation point is a strictly positive loss vector p=(p1,p2,p3).
For weights w in the simplex, the Tchebycheff shadow is

    tau_P(w) = min_p max_i w_i p_i.

This module implements two exact floating-point calculations based on the
perspective map x_i = w_i/t:

1.  Absolute integral R2 value

        R2(P) = integral_Delta tau_P(w) dw

    computed as R2({a}) - (R2({a}) - R2(P)) for any fixed dominated anchor a.

2.  Anchor-normalized improvement

        I_a(P) = R2({a}) - R2(P)

    computed as a weighted anchored-box difference in reciprocal space:

        integral_{U(1/P) minus U(1/a)} (x+y+z)^(-4) dx dy dz.

The code contains a transparent z-sweep box emitter for reproducibility.  The
weighted summation routine can also consume boxes generated by any 3-D
hypervolume box decomposition algorithm.  A tree-free O(n log n) emitter with
O(n) output boxes can therefore be plugged in without changing the weighted
integration step.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from typing import List, Sequence, Tuple
import csv
import math
import time

import numpy as np

Box = Tuple[float, float, float, float, float, float]  # xlo,xhi,ylo,yhi,zlo,zhi


@dataclass
class PerspectiveResult:
    value: float
    num_union_boxes: int
    num_integrated_boxes: int
    cpu_seconds: float


def validate_positive_points(points: Sequence[Sequence[float]]) -> np.ndarray:
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must have shape (n, 3)")
    if len(pts) == 0:
        raise ValueError("at least one point is required")
    if not np.all(np.isfinite(pts)) or np.any(pts <= 0.0):
        raise ValueError("all coordinates must be finite and strictly positive")
    return pts


def reciprocal_points(points: Sequence[Sequence[float]]) -> np.ndarray:
    return 1.0 / validate_positive_points(points)


def box_volume_positive(box: Box, tol: float = 1e-15) -> bool:
    x0, x1, y0, y1, z0, z1 = box
    return (x1 - x0) > tol and (y1 - y0) > tol and (z1 - z0) > tol


def intersect_boxes(a: Box, b: Box, tol: float = 1e-15) -> Box | None:
    x0 = max(a[0], b[0]); x1 = min(a[1], b[1])
    y0 = max(a[2], b[2]); y1 = min(a[3], b[3])
    z0 = max(a[4], b[4]); z1 = min(a[5], b[5])
    out = (x0, x1, y0, y1, z0, z1)
    return out if box_volume_positive(out, tol=tol) else None


def subtract_box(box: Box, cut: Box, tol: float = 1e-15) -> List[Box]:
    """Return a disjoint list of boxes whose union is box minus cut."""
    inter = intersect_boxes(box, cut, tol=tol)
    if inter is None:
        return [box] if box_volume_positive(box, tol=tol) else []
    if all(abs(inter[i] - box[i]) <= tol for i in range(6)):
        return []

    x0, x1, y0, y1, z0, z1 = box
    ix0, ix1, iy0, iy1, iz0, iz1 = inter
    pieces: List[Box] = []

    # Left and right x slabs.
    for candidate in [(x0, ix0, y0, y1, z0, z1), (ix1, x1, y0, y1, z0, z1)]:
        if box_volume_positive(candidate, tol=tol):
            pieces.append(candidate)

    # Middle x slab, split below and above the intersection in y.
    mx0, mx1 = ix0, ix1
    for candidate in [(mx0, mx1, y0, iy0, z0, z1), (mx0, mx1, iy1, y1, z0, z1)]:
        if box_volume_positive(candidate, tol=tol):
            pieces.append(candidate)

    # Middle x and y slab, split below and above the intersection in z.
    my0, my1 = iy0, iy1
    for candidate in [(mx0, mx1, my0, my1, z0, iz0), (mx0, mx1, my0, my1, iz1, z1)]:
        if box_volume_positive(candidate, tol=tol):
            pieces.append(candidate)
    return pieces


def _F(x: float, y: float, z: float) -> float:
    """Antiderivative for density (x+y+z)^(-4)."""
    if math.isinf(x) or math.isinf(y) or math.isinf(z):
        return 0.0
    s = x + y + z
    if s <= 0.0:
        raise ValueError("weighted box integral encountered the singular origin")
    return -1.0 / (6.0 * s)


def weighted_box_integral(box: Box) -> float:
    """Integral of (x+y+z)^(-4) over one axis-aligned box.

    Infinite upper bounds are allowed.  Corner terms containing infinity are
    interpreted as zero.
    """
    x0, x1, y0, y1, z0, z1 = box
    total = 0.0
    xs = [x0, x1]; ys = [y0, y1]; zs = [z0, z1]
    for ex, ey, ez in product([0, 1], repeat=3):
        sign = (-1.0) ** (3 - (ex + ey + ez))
        total += sign * _F(xs[ex], ys[ey], zs[ez])
    return max(0.0, total)


def complement_of_anchor_box_3d(anchor_corner: Sequence[float]) -> List[Box]:
    """Disjoint decomposition of R^3_+ minus [0,u1]x[0,u2]x[0,u3]."""
    u1, u2, u3 = map(float, anchor_corner)
    inf = math.inf
    return [
        (u1, inf, 0.0, inf, 0.0, inf),
        (0.0, u1, u2, inf, 0.0, inf),
        (0.0, u1, 0.0, u2, u3, inf),
    ]


def single_point_r2_perspective(point: Sequence[float]) -> float:
    """Exact unnormalised integral R2 value of a single positive point."""
    p = validate_positive_points([point])[0]
    corner = 1.0 / p
    return sum(weighted_box_integral(box) for box in complement_of_anchor_box_3d(corner))


def skyline_rectangles_2d(active_xy: np.ndarray, tol: float = 1e-14) -> List[Tuple[float, float, float, float]]:
    """Disjoint rectangles covering the union of 2-D anchored rectangles."""
    if len(active_xy) == 0:
        return []
    by_y = {}
    for x, y in active_xy:
        if x <= tol or y <= tol:
            continue
        by_y[float(y)] = max(float(x), by_y.get(float(y), 0.0))
    candidates = sorted([(x, y) for y, x in by_y.items()], key=lambda p: -p[1])

    kept = []
    max_x = -math.inf
    for x, y in candidates:
        if x > max_x + tol:
            kept.append((x, y))
            max_x = x
    kept.sort(key=lambda p: p[1])

    rects = []
    prev_y = 0.0
    for x, y in kept:
        if y > prev_y + tol and x > tol:
            rects.append((0.0, float(x), float(prev_y), float(y)))
            prev_y = float(y)
    return rects


def decompose_union_boxes_sweep(corners: Sequence[Sequence[float]], tol: float = 1e-14) -> List[Box]:
    """Disjoint z-sweep decomposition of a 3-D anchored-box union.

    This implementation is transparent rather than asymptotically optimal.  It
    emits boxes covering union_q [0,q1]x[0,q2]x[0,q3].  The report separates
    the box emitter from the weighted integration step, so this emitter can be
    replaced by a tree-free O(n log n) hypervolume decomposition.
    """
    pts = validate_positive_points(corners)
    z_levels = sorted({0.0, *[float(z) for _, _, z in pts]})
    boxes: List[Box] = []
    for k in range(len(z_levels) - 1):
        z0, z1 = z_levels[k], z_levels[k + 1]
        if z1 <= z0 + tol:
            continue
        active = pts[pts[:, 2] >= z1 - tol][:, :2]
        for x0, x1, y0, y1 in skyline_rectangles_2d(active, tol=tol):
            b = (x0, x1, y0, y1, z0, z1)
            if box_volume_positive(b, tol=tol):
                boxes.append(b)
    return boxes


def perspective_r2_improvement(points: Sequence[Sequence[float]], anchor: Sequence[float]) -> PerspectiveResult:
    """Compute R2({anchor}) - R2(points) by perspective-weighted boxes."""
    start = time.process_time()
    pts = validate_positive_points(points)
    anchor = np.asarray(anchor, dtype=float)
    if anchor.shape != (3,) or np.any(anchor <= 0.0):
        raise ValueError("anchor must be a positive vector of length 3")
    if np.any(anchor < pts.max(axis=0) - 1e-14):
        raise ValueError("anchor must be componentwise worse: anchor_i >= max_p p_i")

    corners = reciprocal_points(pts)
    anchor_corner = tuple((1.0 / anchor).tolist())
    anchor_box: Box = (0.0, anchor_corner[0], 0.0, anchor_corner[1], 0.0, anchor_corner[2])
    union_boxes = decompose_union_boxes_sweep(corners)

    value = 0.0
    integrated = 0
    for box in union_boxes:
        for piece in subtract_box(box, anchor_box):
            value += weighted_box_integral(piece)
            integrated += 1
    return PerspectiveResult(float(value), len(union_boxes), integrated, time.process_time() - start)


def perspective_r2_value(points: Sequence[Sequence[float]], anchor: Sequence[float] | None = None) -> PerspectiveResult:
    """Compute the absolute integral R2 value via anchor reconstruction.

    If no anchor is supplied, a deterministic componentwise-worse anchor is
    chosen automatically: 1.1 * max(points, axis=0).  Any strictly dominated
    anchor gives the same final R2(P) up to floating point roundoff.
    """
    start = time.process_time()
    pts = validate_positive_points(points)
    if anchor is None:
        anchor = 1.1 * pts.max(axis=0)
    anchor = np.asarray(anchor, dtype=float)
    r2_anchor = single_point_r2_perspective(anchor)
    gain = perspective_r2_improvement(pts, anchor)
    return PerspectiveResult(r2_anchor - gain.value, gain.num_union_boxes, gain.num_integrated_boxes,
                             time.process_time() - start)


def monte_carlo_r2_value(points: Sequence[Sequence[float]], samples: int = 200_000, seed: int = 0) -> Tuple[float, float]:
    """Monte Carlo estimate of the unnormalised R2 integral over Delta_2."""
    pts = validate_positive_points(points)
    rng = np.random.default_rng(seed)
    u = rng.random((samples, 2))
    flip = u.sum(axis=1) > 1.0
    u[flip] = 1.0 - u[flip]
    w1 = u[:, 0]
    w2 = u[:, 1]
    w3 = 1.0 - w1 - w2
    vals = np.minimum.reduce([
        np.maximum.reduce([p[0] * w1, p[1] * w2, p[2] * w3]) for p in pts
    ])
    area = 0.5
    return area * float(vals.mean()), area * float(vals.std(ddof=1) / math.sqrt(samples))


def monte_carlo_r2_improvement(points: Sequence[Sequence[float]], anchor: Sequence[float], samples: int = 200_000,
                               seed: int = 0) -> Tuple[float, float]:
    """Monte Carlo estimate of the anchor-normalised improvement integral."""
    pts = validate_positive_points(points)
    anchor = np.asarray(anchor, dtype=float)
    rng = np.random.default_rng(seed)
    u = rng.random((samples, 2))
    flip = u.sum(axis=1) > 1.0
    u[flip] = 1.0 - u[flip]
    w1 = u[:, 0]
    w2 = u[:, 1]
    w3 = 1.0 - w1 - w2
    anchor_vals = np.maximum.reduce([anchor[0] * w1, anchor[1] * w2, anchor[2] * w3])
    point_vals = np.minimum.reduce([
        np.maximum.reduce([p[0] * w1, p[1] * w2, p[2] * w3]) for p in pts
    ])
    gains = anchor_vals - point_vals
    area = 0.5
    return area * float(gains.mean()), area * float(gains.std(ddof=1) / math.sqrt(samples))


def example_instances() -> List[Tuple[str, np.ndarray, np.ndarray]]:
    return [
        ("three_point_front", np.array([
            [0.30, 1.20, 1.00],
            [0.65, 0.70, 0.85],
            [1.10, 0.40, 0.55],
        ]), np.array([1.40, 1.45, 1.25])),
        ("four_point_front", np.array([
            [0.30, 1.20, 1.00],
            [0.65, 0.70, 0.85],
            [1.10, 0.40, 0.55],
            [0.95, 0.95, 0.25],
        ]), np.array([1.40, 1.45, 1.25])),
        ("five_point_front", np.array([
            [0.25, 1.40, 1.10],
            [0.40, 1.05, 0.95],
            [0.72, 0.74, 0.82],
            [1.04, 0.55, 0.60],
            [1.20, 0.35, 0.45],
        ]), np.array([1.50, 1.55, 1.30])),
    ]


def run_verification_csv(path: str = "verification_results.csv", samples: int = 100_000) -> None:
    from r2_subdivision3d import exact_r2_3d  # local file bundled with this script

    rows = []
    for name, pts, anchor in example_instances():
        persp_abs = perspective_r2_value(pts, anchor)
        persp_gain = perspective_r2_improvement(pts, anchor)
        sub_set = exact_r2_3d(pts).value
        sub_anchor = exact_r2_3d(np.array([anchor])).value
        sub_gain = sub_anchor - sub_set
        mc_abs, se_abs = monte_carlo_r2_value(pts, samples=samples, seed=42)
        mc_gain, se_gain = monte_carlo_r2_improvement(pts, anchor, samples=samples, seed=43)
        rows.append({
            "instance": name,
            "n": len(pts),
            "anchor": repr(anchor.tolist()),
            "perspective_r2": f"{persp_abs.value:.12g}",
            "subdivision_r2": f"{sub_set:.12g}",
            "absolute_r2_difference": f"{abs(persp_abs.value - sub_set):.3e}",
            "mc_r2": f"{mc_abs:.12g}",
            "mc_r2_95ci_halfwidth": f"{1.96*se_abs:.3e}",
            "perspective_improvement": f"{persp_gain.value:.12g}",
            "subdivision_improvement": f"{sub_gain:.12g}",
            "improvement_difference": f"{abs(persp_gain.value - sub_gain):.3e}",
            "mc_improvement": f"{mc_gain:.12g}",
            "mc_improvement_95ci_halfwidth": f"{1.96*se_gain:.3e}",
            "union_boxes": persp_gain.num_union_boxes,
            "integrated_boxes_after_anchor_subtraction": persp_gain.num_integrated_boxes,
            "cpu_seconds_perspective_r2": f"{persp_abs.cpu_seconds:.6f}",
        })
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    run_verification_csv()
    print("wrote verification_results.csv")
